Fix compile errors with XC16 v2.00 (#165)
* Remove calls to `min()` since I can't find it in the headers of XC16 v2.00

The compiler error is:
> ../openocd.c:215:7: error: implicit declaration of function 'min'

I suspect there _is_ a `min` function we could use for readability, but I don't see it
declared anywhere in XC16's `microchip/xc16/v2.00/include` directory

* Fix comparison between pointer and integer, simplify

Instead of comparing an integer (aka char) against NULL, simply use the short form of
the ternary operator. Documented here: https://gcc.gnu.org/onlinedocs/gcc/Conditionals.html

Fixes compiler warning/error:

> ../proc_menu.c: In function 'remove_current_character_from_command_line':
> ../proc_menu.c:1847:50: error: comparison between pointer and integer